
version: "3.9"
services:
  nginx:
    build: 
      context: ngnix
    #image: nobre/ngnix:desafio02
    container_name: nginx
    ports:
      - "8080:80"
    networks:
    - node-network
    depends_on:
      - appnode

  appnode:
    build: 
      context: node
    #image: nobre/node:desafio02
    container_name: appnode
    entrypoint: dockerize -wait tcp://dbmysql:3306 -timeout 10s  node index.js 
    #command: node index.js 
    networks:
      - node-network
    volumes:
      - ./node:/usr/scr/app/
    tty: true
    ports:
      - "3000:3000" 
    depends_on:
      - dbmysql

  dbmysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: dbmysql
    restart: always
    tty: true
    volumes:
      - /home/nobre/docker/mysql/file_mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge


